logging:
  config: classpath:logback-spring.xml
  level:
    com:
      liangjiange:
        devopsbackstage: debug
    org:
      springframework:
        security: debug


#配置数据源
spring:
  datasource:
    url: jdbc:mysql://mysql-test:3306/devops_backstage_test_db?serverTimezone=Asia/Shanghai
    username: root
    druid:
      password: 123456

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #这个配置会将执行的sql打印出来，在开发或测试的时候可以用